package wordnet;

enum WORDNET_RELATIONS {
	ADV_POINTER_SYMBOL_ANTONYM ("!"),
	ADV_POINTER_SYMBOL_DERIVED_FROM_ADJECTIVE ("\\"), // link to nouns or verbs
	ADV_POINTER_SYMBOL_DOMAIN_OF_SYNSET_TOPIC (";c"),
	ADV_POINTER_SYMBOL_DOMAIN_OF_SYNSET_REGION (";r"),
	ADV_POINTER_SYMBOL_DOMAIN_OF_SYNSET_USAGE (";u"),
	
	ADJ_POINTER_SYMBOL_ANTONYM ("!"),
	ADJ_POINTER_SYMBOL_SIMILAR_TO ("&"),
	ADJ_POINTER_SYMBOL_PARTICIPLE_OF_VERB ("<"), // link to verbs
	ADJ_POINTER_SYMBOL_PERTAINYM ("\\"), // link to nouns or verbs
	ADJ_POINTER_SYMBOL_ATTRIBUTE ("="),
	ADJ_POINTER_SYMBOL_SEE_ALSO ("^"),
	ADJ_POINTER_SYMBOL_DOMAIN_OF_SYNSET_TOPIC (";c"),
	ADJ_POINTER_SYMBOL_DOMAIN_OF_SYNSET_REGION (";r"),
	ADJ_POINTER_SYMBOL_DOMAIN_OF_SYNSET_USAGE (";u"),

	VRB_POINTER_SYMBOL_ANTONYM ("!"),
	VRB_POINTER_SYMBOL_HYPERNYM ("@"),
	VRB_POINTER_SYMBOL_HYPONYM ("~"),
	VRB_POINTER_SYMBOL_ENTAILMENT ("*"),
	VRB_POINTER_SYMBOL_CAUSE (">"),
	VRB_POINTER_SYMBOL_SEE_ALSO ("^"),
	VRB_POINTER_SYMBOL_VERB_GROUP ("$"),
	VRB_POINTER_SYMBOL_DERIVATIONALLY_RELATED_FROM ("+"),
	VRB_POINTER_SYMBOL_DOMAIN_OF_SYNSET_TOPIC (";c"),
	VRB_POINTER_SYMBOL_DOMAIN_OF_SYNSET_REGION (";r"),
	VRB_POINTER_SYMBOL_DOMAIN_OF_SYNSET_USAGE (";u"),

	NOUN_POINTER_SYMBOL_ANTONYM ("!"),
	NOUN_POINTER_SYMBOL_HYPERNYM ("@"),
	NOUN_POINTER_SYMBOL_INSTANCE_HYPERNYM ("@i"),
	NOUN_POINTER_SYMBOL_HYPONYM ("~"),
	NOUN_POINTER_SYMBOL_INSTANCE_HYPONYM ("~i"),
	NOUN_POINTER_SYMBOL_MEMBER_HOLONYM ("#m"),
	NOUN_POINTER_SYMBOL_SUBSTANCE_HOLONYM ("#s"),
	NOUN_POINTER_SYMBOL_PART_HOLONYM ("#p"),
	NOUN_POINTER_SYMBOL_MEMBER_MERONYM ("%m"),
	NOUN_POINTER_SYMBOL_SUBSTANCE_MERONYM ("%s"),
	NOUN_POINTER_SYMBOL_PART_MERONYM ("%p"),
	NOUN_POINTER_SYMBOL_ATTRIBUTE ("="),
	NOUN_POINTER_SYMBOL_DERIVATIONALLY_RELATED_FROM ("+"),
	NOUN_POINTER_SYMBOL_DOMAIN_OF_SYNSET_TOPIC (";c"),
	NOUN_POINTER_SYMBOL_DOMAIN_OF_SYNSET_REGION (";r"),
	NOUN_POINTER_SYMBOL_DOMAIN_OF_SYNSET_USAGE (";u"),
	NOUN_POINTER_SYMBOL_MEMEBER_OF_THIS_DOMAIN_TOPIC ("-c"),
	NOUN_POINTER_SYMBOL_MEMEBER_OF_THIS_DOMAIN_REGION ("-r"),
	NOUN_POINTER_SYMBOL_MEMEBER_OF_THIS_DOMAIN_USAGE ("-u");

	
	private final String type ;
	
	WORDNET_RELATIONS(String type) {
		this.type = type;
	}
	
	String getType() {
		return this.type;
	}
	
}